madera_devis_homepage:
    path:     /
    defaults: { _controller: MaderaDevisBundle:Default:index }

devis_new:
    path:   /devis/new
    defaults: { _controller: MaderaDevisBundle:Default:newDevis }