Madera\DevisBundle\Entity\gammes:
    type: entity
    table: null
    repositoryClass: Madera\DevisBundle\Repository\gammesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idModele:
            type: integer
        nom:
            type: string
            length: 255
    lifecycleCallbacks: {  }
