Madera\DevisBundle\Entity\modulededevis:
    type: entity
    table: null
    repositoryClass: Madera\DevisBundle\Repository\modulededevisRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idDevis:
            type: integer
        idModule:
            type: integer
    lifecycleCallbacks: {  }
