Madera\DevisBundle\Entity\modulesdemodele:
    type: entity
    table: null
    repositoryClass: Madera\DevisBundle\Repository\modulesdemodeleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idModele:
            type: integer
    lifecycleCallbacks: {  }
