<?php

namespace Madera\DevisBundle\Repository;

/**
 * gammesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gammesRepository extends \Doctrine\ORM\EntityRepository
{
}
