<?php

namespace Madera\DevisBundle\Repository;

/**
 * modelesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class modelesRepository extends \Doctrine\ORM\EntityRepository
{
}
