<?php

namespace Madera\DevisBundle\Repository;

/**
 * modulededevisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class modulededevisRepository extends \Doctrine\ORM\EntityRepository
{
}
