<?php

namespace Madera\DevisBundle\Repository;

/**
 * modulesdemodeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class modulesdemodeleRepository extends \Doctrine\ORM\EntityRepository
{
}
